// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type PickContentRelationshipFieldData<
  TRelationship extends
    | prismic.CustomTypeModelFetchCustomTypeLevel1
    | prismic.CustomTypeModelFetchCustomTypeLevel2
    | prismic.CustomTypeModelFetchGroupLevel1
    | prismic.CustomTypeModelFetchGroupLevel2,
  TData extends Record<
    string,
    | prismic.AnyRegularField
    | prismic.GroupField
    | prismic.NestedGroupField
    | prismic.SliceZone
  >,
  TLang extends string,
> =
  // Content relationship fields
  {
    [TSubRelationship in Extract<
      TRelationship["fields"][number],
      prismic.CustomTypeModelFetchContentRelationshipLevel1
    > as TSubRelationship["id"]]: ContentRelationshipFieldWithData<
      TSubRelationship["customtypes"],
      TLang
    >;
  } & // Group
  {
    [TGroup in Extract<
      TRelationship["fields"][number],
      | prismic.CustomTypeModelFetchGroupLevel1
      | prismic.CustomTypeModelFetchGroupLevel2
    > as TGroup["id"]]: TData[TGroup["id"]] extends prismic.GroupField<
      infer TGroupData
    >
      ? prismic.GroupField<
          PickContentRelationshipFieldData<TGroup, TGroupData, TLang>
        >
      : never;
  } & // Other fields
  {
    [TFieldKey in Extract<
      TRelationship["fields"][number],
      string
    >]: TFieldKey extends keyof TData ? TData[TFieldKey] : never;
  };

type ContentRelationshipFieldWithData<
  TCustomType extends
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel1 | string)[]
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel2 | string)[],
  TLang extends string = string,
> = {
  [ID in Exclude<
    TCustomType[number],
    string
  >["id"]]: prismic.ContentRelationshipField<
    ID,
    TLang,
    PickContentRelationshipFieldData<
      Extract<TCustomType[number], { id: ID }>,
      Extract<prismic.Content.AllDocumentTypes, { type: ID }>["data"],
      TLang
    >
  >;
}[Exclude<TCustomType[number], string>["id"]];

type PageDocumentDataSlicesSlice =
  | PricingSlice
  | LongParagraphSlice
  | FaqSlice
  | StepsSlice
  | ComparisonSlice
  | TestimonialsSlice
  | HeroSlice;

/**
 * Content for Page documents
 */
interface PageDocumentData {
  /**
   * Title field in *Page*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: page.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Slice Zone field in *Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<PageDocumentDataSlicesSlice>;
}

/**
 * Page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<PageDocumentData>, "page", Lang>;

type PrivacyPolicyDocumentDataSlicesSlice = LongParagraphSlice | HeroSlice;

/**
 * Content for Privacy Policy documents
 */
interface PrivacyPolicyDocumentData {
  /**
   * Slice Zone field in *Privacy Policy*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: privacy_policy.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<PrivacyPolicyDocumentDataSlicesSlice> /**
   * Meta Title field in *Privacy Policy*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: privacy_policy.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Privacy Policy*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: privacy_policy.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Privacy Policy*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: privacy_policy.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Privacy Policy document from Prismic
 *
 * - **API ID**: `privacy_policy`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PrivacyPolicyDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<PrivacyPolicyDocumentData>,
    "privacy_policy",
    Lang
  >;

/**
 * Content for Settings documents
 */
interface SettingsDocumentData {
  /**
   * Site Title field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.site_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  site_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.meta_description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Settings*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.meta_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Navigation field in *Settings*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.navigation
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  navigation: prismic.Repeatable<
    prismic.LinkField<
      string,
      string,
      unknown,
      prismic.FieldState,
      "Link" | "Button"
    >
  >;
}

/**
 * Settings document from Prismic
 *
 * - **API ID**: `settings`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SettingsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<SettingsDocumentData>,
    "settings",
    Lang
  >;

export type AllDocumentTypes =
  | PageDocument
  | PrivacyPolicyDocument
  | SettingsDocument;

/**
 * Item in *Comparison → Default → Primary → Before*
 */
export interface ComparisonSliceDefaultPrimaryBeforeItem {
  /**
   * Name List field in *Comparison → Default → Primary → Before*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: comparison.default.primary.before[].name_list
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  name_list: prismic.KeyTextField;
}

/**
 * Item in *Comparison → Default → Primary → After*
 */
export interface ComparisonSliceDefaultPrimaryAfterItem {
  /**
   * Name List field in *Comparison → Default → Primary → After*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: comparison.default.primary.after[].name_list
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  name_list: prismic.KeyTextField;
}

/**
 * Item in *Comparison → Secondary → Primary → Before*
 */
export interface ComparisonSliceSecondaryPrimaryBeforeItem {
  /**
   * Name List field in *Comparison → Secondary → Primary → Before*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: comparison.secondary.primary.before[].name_list
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  name_list: prismic.KeyTextField;
}

/**
 * Item in *Comparison → Secondary → Primary → After*
 */
export interface ComparisonSliceSecondaryPrimaryAfterItem {
  /**
   * Name List field in *Comparison → Secondary → Primary → After*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: comparison.secondary.primary.after[].name_list
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  name_list: prismic.KeyTextField;
}

/**
 * Item in *Comparison → Simple Text → Primary → Before*
 */
export interface ComparisonSliceSimpleTextPrimaryBeforeItem {
  /**
   * Name List field in *Comparison → Simple Text → Primary → Before*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: comparison.simpleText.primary.before[].name_list
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  name_list: prismic.KeyTextField;
}

/**
 * Primary content in *Comparison → Default → Primary*
 */
export interface ComparisonSliceDefaultPrimary {
  /**
   * Heading field in *Comparison → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: comparison.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  heading: prismic.KeyTextField;

  /**
   * CTA field in *Comparison → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: comparison.default.primary.cta
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  cta: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;

  /**
   * Before field in *Comparison → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: comparison.default.primary.before[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  before: prismic.GroupField<Simplify<ComparisonSliceDefaultPrimaryBeforeItem>>;

  /**
   * After field in *Comparison → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: comparison.default.primary.after[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  after: prismic.GroupField<Simplify<ComparisonSliceDefaultPrimaryAfterItem>>;
}

/**
 * Default variation for Comparison Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ComparisonSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ComparisonSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *Comparison → Secondary → Primary*
 */
export interface ComparisonSliceSecondaryPrimary {
  /**
   * Heading field in *Comparison → Secondary → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: comparison.secondary.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  heading: prismic.KeyTextField;

  /**
   * First Column Heading field in *Comparison → Secondary → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: comparison.secondary.primary.first_column_heading
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  first_column_heading: prismic.KeyTextField;

  /**
   * Before field in *Comparison → Secondary → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: comparison.secondary.primary.before[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  before: prismic.GroupField<
    Simplify<ComparisonSliceSecondaryPrimaryBeforeItem>
  >;

  /**
   * Second Column Heading field in *Comparison → Secondary → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: comparison.secondary.primary.second_column_heading
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  second_column_heading: prismic.KeyTextField;

  /**
   * After field in *Comparison → Secondary → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: comparison.secondary.primary.after[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  after: prismic.GroupField<Simplify<ComparisonSliceSecondaryPrimaryAfterItem>>;
}

/**
 * Secondary variation for Comparison Slice
 *
 * - **API ID**: `secondary`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ComparisonSliceSecondary = prismic.SharedSliceVariation<
  "secondary",
  Simplify<ComparisonSliceSecondaryPrimary>,
  never
>;

/**
 * Primary content in *Comparison → Simple Text → Primary*
 */
export interface ComparisonSliceSimpleTextPrimary {
  /**
   * First Column Heading field in *Comparison → Simple Text → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: comparison.simpleText.primary.first_column_heading
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  first_column_heading: prismic.KeyTextField;

  /**
   * Before field in *Comparison → Simple Text → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: comparison.simpleText.primary.before[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  before: prismic.GroupField<
    Simplify<ComparisonSliceSimpleTextPrimaryBeforeItem>
  >;

  /**
   * Second Column Heading field in *Comparison → Simple Text → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: comparison.simpleText.primary.second_column_heading
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  second_column_heading: prismic.KeyTextField;

  /**
   * Text field in *Comparison → Simple Text → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: comparison.simpleText.primary.text
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  text: prismic.RichTextField;
}

/**
 * Simple Text variation for Comparison Slice
 *
 * - **API ID**: `simpleText`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ComparisonSliceSimpleText = prismic.SharedSliceVariation<
  "simpleText",
  Simplify<ComparisonSliceSimpleTextPrimary>,
  never
>;

/**
 * Slice variation for *Comparison*
 */
type ComparisonSliceVariation =
  | ComparisonSliceDefault
  | ComparisonSliceSecondary
  | ComparisonSliceSimpleText;

/**
 * Comparison Shared Slice
 *
 * - **API ID**: `comparison`
 * - **Description**: Comparison
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ComparisonSlice = prismic.SharedSlice<
  "comparison",
  ComparisonSliceVariation
>;

/**
 * Item in *Faq → Default → Primary → Accordion*
 */
export interface FaqSliceDefaultPrimaryAccordionItem {
  /**
   * Title field in *Faq → Default → Primary → Accordion*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faq.default.primary.accordion[].title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Text field in *Faq → Default → Primary → Accordion*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faq.default.primary.accordion[].text
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  text: prismic.RichTextField;
}

/**
 * Primary content in *Faq → Default → Primary*
 */
export interface FaqSliceDefaultPrimary {
  /**
   * Heading field in *Faq → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faq.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  heading: prismic.KeyTextField;

  /**
   * Accordion field in *Faq → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: faq.default.primary.accordion[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  accordion: prismic.GroupField<Simplify<FaqSliceDefaultPrimaryAccordionItem>>;
}

/**
 * Default variation for Faq Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FaqSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<FaqSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Faq*
 */
type FaqSliceVariation = FaqSliceDefault;

/**
 * Faq Shared Slice
 *
 * - **API ID**: `faq`
 * - **Description**: Faq
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FaqSlice = prismic.SharedSlice<"faq", FaqSliceVariation>;

/**
 * Primary content in *Hero → Full Hero → Primary*
 */
export interface HeroSliceDefaultPrimary {
  /**
   * Badge field in *Hero → Full Hero → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.badge
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  badge: prismic.KeyTextField;

  /**
   * Heading field in *Hero → Full Hero → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  heading: prismic.RichTextField;

  /**
   * Body field in *Hero → Full Hero → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.body
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  body: prismic.RichTextField;

  /**
   * CTAs field in *Hero → Full Hero → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.ctas
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  ctas: prismic.Repeatable<
    prismic.LinkField<
      string,
      string,
      unknown,
      prismic.FieldState,
      "Primary" | "Secondary"
    >
  >;

  /**
   * VideoLink field in *Hero → Full Hero → Primary*
   *
   * - **Field Type**: Embed
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.videolink
   * - **Documentation**: https://prismic.io/docs/fields/embed
   */
  videolink: prismic.EmbedField;
}

/**
 * Full Hero variation for Hero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *Hero → Secondary → Primary*
 */
export interface HeroSliceSecondaryPrimary {
  /**
   * Heading field in *Hero → Secondary → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.secondary.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  heading: prismic.RichTextField;

  /**
   * Body field in *Hero → Secondary → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.secondary.primary.body
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  body: prismic.RichTextField;

  /**
   * CTAs field in *Hero → Secondary → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.secondary.primary.ctas
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  ctas: prismic.Repeatable<
    prismic.LinkField<
      string,
      string,
      unknown,
      prismic.FieldState,
      "Primary" | "Secondary"
    >
  >;

  /**
   * VideoLink field in *Hero → Secondary → Primary*
   *
   * - **Field Type**: Embed
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.secondary.primary.videolink
   * - **Documentation**: https://prismic.io/docs/fields/embed
   */
  videolink: prismic.EmbedField;
}

/**
 * Secondary variation for Hero Slice
 *
 * - **API ID**: `secondary`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroSliceSecondary = prismic.SharedSliceVariation<
  "secondary",
  Simplify<HeroSliceSecondaryPrimary>,
  never
>;

/**
 * Primary content in *Hero → With Image → Primary*
 */
export interface HeroSliceWithImagePrimary {
  /**
   * Heading field in *Hero → With Image → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.withImage.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  heading: prismic.RichTextField;

  /**
   * Body field in *Hero → With Image → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.withImage.primary.body
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  body: prismic.RichTextField;

  /**
   * CTAs field in *Hero → With Image → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.withImage.primary.ctas
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  ctas: prismic.Repeatable<
    prismic.LinkField<
      string,
      string,
      unknown,
      prismic.FieldState,
      "Primary" | "Secondary"
    >
  >;

  /**
   * Image field in *Hero → With Image → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.withImage.primary.image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;
}

/**
 * With Image variation for Hero Slice
 *
 * - **API ID**: `withImage`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroSliceWithImage = prismic.SharedSliceVariation<
  "withImage",
  Simplify<HeroSliceWithImagePrimary>,
  never
>;

/**
 * Slice variation for *Hero*
 */
type HeroSliceVariation =
  | HeroSliceDefault
  | HeroSliceSecondary
  | HeroSliceWithImage;

/**
 * Hero Shared Slice
 *
 * - **API ID**: `hero`
 * - **Description**: Hero
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroSlice = prismic.SharedSlice<"hero", HeroSliceVariation>;

/**
 * Primary content in *LongParagraph → Default → Primary*
 */
export interface LongParagraphSliceDefaultPrimary {
  /**
   * Text field in *LongParagraph → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: long_paragraph.default.primary.text
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  text: prismic.RichTextField;
}

/**
 * Default variation for LongParagraph Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type LongParagraphSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<LongParagraphSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *LongParagraph*
 */
type LongParagraphSliceVariation = LongParagraphSliceDefault;

/**
 * LongParagraph Shared Slice
 *
 * - **API ID**: `long_paragraph`
 * - **Description**: LongParagraph
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type LongParagraphSlice = prismic.SharedSlice<
  "long_paragraph",
  LongParagraphSliceVariation
>;

/**
 * Item in *Pricing → Default → Primary → First Column*
 */
export interface PricingSliceDefaultPrimaryFirstColumnItem {
  /**
   * Text field in *Pricing → Default → Primary → First Column*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: pricing.default.primary.first_column[].text
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  text: prismic.KeyTextField;
}

/**
 * Primary content in *Pricing → Default → Primary*
 */
export interface PricingSliceDefaultPrimary {
  /**
   * Heading field in *Pricing → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: pricing.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  heading: prismic.KeyTextField;

  /**
   * Text field in *Pricing → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: pricing.default.primary.text
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  text: prismic.KeyTextField;

  /**
   * Badge field in *Pricing → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: pricing.default.primary.badge
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  badge: prismic.KeyTextField;

  /**
   * Price field in *Pricing → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: pricing.default.primary.price
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  price: prismic.KeyTextField;

  /**
   * Subheading field in *Pricing → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: pricing.default.primary.subheading
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  subheading: prismic.KeyTextField;

  /**
   * First Column field in *Pricing → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: pricing.default.primary.first_column[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  first_column: prismic.GroupField<
    Simplify<PricingSliceDefaultPrimaryFirstColumnItem>
  >;

  /**
   * Button field in *Pricing → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: pricing.default.primary.button
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  button: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;

  /**
   * Second Column Heading field in *Pricing → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: pricing.default.primary.second_column_heading
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  second_column_heading: prismic.KeyTextField;

  /**
   * Second Column Text field in *Pricing → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: pricing.default.primary.second_column_text
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  second_column_text: prismic.RichTextField;

  /**
   * Second Button  field in *Pricing → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: pricing.default.primary.second_button
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  second_button: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * Default variation for Pricing Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type PricingSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<PricingSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Pricing*
 */
type PricingSliceVariation = PricingSliceDefault;

/**
 * Pricing Shared Slice
 *
 * - **API ID**: `pricing`
 * - **Description**: Pricing
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type PricingSlice = prismic.SharedSlice<
  "pricing",
  PricingSliceVariation
>;

/**
 * Item in *Steps → Default → Primary → Tiles*
 */
export interface StepsSliceDefaultPrimaryTilesItem {
  /**
   * SVG field in *Steps → Default → Primary → Tiles*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: steps.default.primary.tiles[].svg
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  svg: prismic.KeyTextField;

  /**
   * Step Order field in *Steps → Default → Primary → Tiles*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: steps.default.primary.tiles[].step_order
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  step_order: prismic.KeyTextField;

  /**
   * Heading field in *Steps → Default → Primary → Tiles*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: steps.default.primary.tiles[].heading
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  heading: prismic.KeyTextField;

  /**
   * Text field in *Steps → Default → Primary → Tiles*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: steps.default.primary.tiles[].text
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  text: prismic.KeyTextField;
}

/**
 * Primary content in *Steps → Default → Primary*
 */
export interface StepsSliceDefaultPrimary {
  /**
   * Heading field in *Steps → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: steps.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  heading: prismic.KeyTextField;

  /**
   * Text field in *Steps → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: steps.default.primary.text
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  text: prismic.KeyTextField;

  /**
   * Tiles field in *Steps → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: steps.default.primary.tiles[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  tiles: prismic.GroupField<Simplify<StepsSliceDefaultPrimaryTilesItem>>;
}

/**
 * Default variation for Steps Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type StepsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<StepsSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Steps*
 */
type StepsSliceVariation = StepsSliceDefault;

/**
 * Steps Shared Slice
 *
 * - **API ID**: `steps`
 * - **Description**: Steps
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type StepsSlice = prismic.SharedSlice<"steps", StepsSliceVariation>;

/**
 * Item in *Testimonials → Default → Primary → Testimonial*
 */
export interface TestimonialsSliceDefaultPrimaryTestimonialItem {
  /**
   * Image field in *Testimonials → Default → Primary → Testimonial*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonials.default.primary.testimonial[].image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;

  /**
   * Text field in *Testimonials → Default → Primary → Testimonial*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonials.default.primary.testimonial[].text
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  text: prismic.RichTextField;

  /**
   * Name field in *Testimonials → Default → Primary → Testimonial*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonials.default.primary.testimonial[].name
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  name: prismic.KeyTextField;

  /**
   * Company field in *Testimonials → Default → Primary → Testimonial*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonials.default.primary.testimonial[].company
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  company: prismic.KeyTextField;
}

/**
 * Primary content in *Testimonials → Default → Primary*
 */
export interface TestimonialsSliceDefaultPrimary {
  /**
   * Heading field in *Testimonials → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonials.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  heading: prismic.KeyTextField;

  /**
   * Testimonial field in *Testimonials → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonials.default.primary.testimonial[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  testimonial: prismic.GroupField<
    Simplify<TestimonialsSliceDefaultPrimaryTestimonialItem>
  >;
}

/**
 * Default variation for Testimonials Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type TestimonialsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TestimonialsSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Testimonials*
 */
type TestimonialsSliceVariation = TestimonialsSliceDefault;

/**
 * Testimonials Shared Slice
 *
 * - **API ID**: `testimonials`
 * - **Description**: Testimonials
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type TestimonialsSlice = prismic.SharedSlice<
  "testimonials",
  TestimonialsSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      PageDocument,
      PageDocumentData,
      PageDocumentDataSlicesSlice,
      PrivacyPolicyDocument,
      PrivacyPolicyDocumentData,
      PrivacyPolicyDocumentDataSlicesSlice,
      SettingsDocument,
      SettingsDocumentData,
      AllDocumentTypes,
      ComparisonSlice,
      ComparisonSliceDefaultPrimaryBeforeItem,
      ComparisonSliceDefaultPrimaryAfterItem,
      ComparisonSliceDefaultPrimary,
      ComparisonSliceSecondaryPrimaryBeforeItem,
      ComparisonSliceSecondaryPrimaryAfterItem,
      ComparisonSliceSecondaryPrimary,
      ComparisonSliceSimpleTextPrimaryBeforeItem,
      ComparisonSliceSimpleTextPrimary,
      ComparisonSliceVariation,
      ComparisonSliceDefault,
      ComparisonSliceSecondary,
      ComparisonSliceSimpleText,
      FaqSlice,
      FaqSliceDefaultPrimaryAccordionItem,
      FaqSliceDefaultPrimary,
      FaqSliceVariation,
      FaqSliceDefault,
      HeroSlice,
      HeroSliceDefaultPrimary,
      HeroSliceSecondaryPrimary,
      HeroSliceWithImagePrimary,
      HeroSliceVariation,
      HeroSliceDefault,
      HeroSliceSecondary,
      HeroSliceWithImage,
      LongParagraphSlice,
      LongParagraphSliceDefaultPrimary,
      LongParagraphSliceVariation,
      LongParagraphSliceDefault,
      PricingSlice,
      PricingSliceDefaultPrimaryFirstColumnItem,
      PricingSliceDefaultPrimary,
      PricingSliceVariation,
      PricingSliceDefault,
      StepsSlice,
      StepsSliceDefaultPrimaryTilesItem,
      StepsSliceDefaultPrimary,
      StepsSliceVariation,
      StepsSliceDefault,
      TestimonialsSlice,
      TestimonialsSliceDefaultPrimaryTestimonialItem,
      TestimonialsSliceDefaultPrimary,
      TestimonialsSliceVariation,
      TestimonialsSliceDefault,
    };
  }
}
