// Code generated by Slice Machine. DO NOT EDIT.

import { defineAsyncComponent } from "vue";
import { defineSliceZoneComponents } from "@prismicio/vue";

export const components = defineSliceZoneComponents({
  comparison: defineAsyncComponent(() => import("./Comparison/index.vue")),
  hero: defineAsyncComponent(() => import("./Hero/index.vue")),
  pricing: defineAsyncComponent(() => import("./Pricing/index.vue")),
  steps: defineAsyncComponent(() => import("./Steps/index.vue")),
  testimonials: defineAsyncComponent(() => import("./Testimonials/index.vue")),
});
